//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMAO.Rapports {

    using System;
    using System.ComponentModel;

    
    
    //public class DemandeT : ReportClass {
        
    //    public DemandeT() {
    //    }
        
    //    public override string ResourceName {
    //        get {
    //            return "DemandeT.rpt";
    //        }
    //        set {
    //            // Do nothing
    //        }
    //    }
        
    //    public override bool NewGenerator {
    //        get {
    //            return true;
    //        }
    //        set {
    //            // Do nothing
    //        }
    //    }
        
    //    public override string FullResourceName {
    //        get {
    //            return "GMAO.Rapports.DemandeT.rpt";
    //        }
    //        set {
    //            // Do nothing
    //        }
    //    }
        
    //    [Browsable(false)]
    //    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    //    public CrystalDecisions.CrystalReports.Engine.Section ReportHeaderSection1 {
    //        get {
    //            return this.ReportDefinition.Sections[0];
    //        }
    //    }
        
    //    [Browsable(false)]
    //    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    //    public CrystalDecisions.CrystalReports.Engine.Section PageHeaderSection1 {
    //        get {
    //            return this.ReportDefinition.Sections[1];
    //        }
    //    }
        
    //    [Browsable(false)]
    //    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    //    public CrystalDecisions.CrystalReports.Engine.Section DetailSection1 {
    //        get {
    //            return this.ReportDefinition.Sections[2];
    //        }
    //    }
        
    //    [Browsable(false)]
    //    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    //    public CrystalDecisions.CrystalReports.Engine.Section ReportFooterSection1 {
    //        get {
    //            return this.ReportDefinition.Sections[3];
    //        }
    //    }
        
    //    [Browsable(false)]
    //    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    //    public CrystalDecisions.CrystalReports.Engine.Section ReportFooterSection2 {
    //        get {
    //            return this.ReportDefinition.Sections[4];
    //        }
    //    }
        
    //    [Browsable(false)]
    //    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    //    public CrystalDecisions.CrystalReports.Engine.Section ReportFooterSection3 {
    //        get {
    //            return this.ReportDefinition.Sections[5];
    //        }
    //    }
        
    //    [Browsable(false)]
    //    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    //    public CrystalDecisions.CrystalReports.Engine.Section PageFooterSection1 {
    //        get {
    //            return this.ReportDefinition.Sections[6];
    //        }
    //    }
    //}
    
    //[System.Drawing.ToolboxBitmapAttribute(typeof(CrystalDecisions.Shared.ExportOptions), "report.bmp")]
    //public class CachedDemandeT : Component, ICachedReport {
        
    //    public CachedDemandeT() {
    //    }
        
    //    [Browsable(false)]
    //    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    //    public virtual bool IsCacheable {
    //        get {
    //            return true;
    //        }
    //        set {
    //            // 
    //        }
    //    }
        
    //    [Browsable(false)]
    //    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    //    public virtual bool ShareDBLogonInfo {
    //        get {
    //            return false;
    //        }
    //        set {
    //            // 
    //        }
    //    }
        
    //    [Browsable(false)]
    //    [DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    //    public virtual System.TimeSpan CacheTimeOut {
    //        get {
    //            return CachedReportConstants.DEFAULT_TIMEOUT;
    //        }
    //        set {
    //            // 
    //        }
    //    }
        
    //    public virtual CrystalDecisions.CrystalReports.Engine.ReportDocument CreateReport() {
    //        DemandeT rpt = new DemandeT();
    //        rpt.Site = this.Site;
    //        return rpt;
    //    }
        
    //    public virtual string GetCustomizedCacheKey(RequestContext request) {
    //        String key = null;
    //        // // The following is the code used to generate the default
    //        // // cache key for caching report jobs in the ASP.NET Cache.
    //        // // Feel free to modify this code to suit your needs.
    //        // // Returning key == null causes the default cache key to
    //        // // be generated.
    //        // 
    //        // key = RequestContext.BuildCompleteCacheKey(
    //        //     request,
    //        //     null,       // sReportFilename
    //        //     this.GetType(),
    //        //     this.ShareDBLogonInfo );
    //        return key;
    //    }
    //}
}
