// <auto-generated />
using GMAO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GMAO.Migrations
{
    [DbContext(typeof(GMAOContext))]
    [Migration("20220617095211_FournisseurPieces")]
    partial class FournisseurPieces
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GMAO.Models.FournisseurPiece", b =>
                {
                    b.Property<string>("CodeFournisseur")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodePiece")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Devise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PAchat")
                        .HasColumnType("real");

                    b.Property<float>("Previent")
                        .HasColumnType("real");

                    b.Property<string>("RefFrs")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodeFournisseur");

                    b.ToTable("FournisseurPiece");
                });
#pragma warning restore 612, 618
        }
    }
}
